### ISSUE TITLE
Not able to install feature `odl-atrium-all`

### ISSUE THREAD

**Issue by subh007** [OpenNetworkingFoundation/ATRIUM#3]
I tried to install the feature `odl-atrium-all` but I'm seeing following error.

```
feature:install odl-atrium-all
Error executing command: Can't install feature odl-atrium-all/0.0.0:
Could not start bundle mvn:org.opendaylight.atrium/routingconfig-impl/1.0-SNAPSHOT in feature(s) atrium-routingconfig-1.0-SNAPSHOT: The bundle "org.opendaylight.atrium.routingconfig-impl_1.0.0.SNAPSHOT [273]" could not be resolved. Reason: Missing Constraint: Import-Package: org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.hostservice.api.rev150725; version="[1.0.0,2.0.0)"
```

**Comment by mknair75** [comment]
As indicated in the README, the correct order for installing features is 
1) feature:install odl-l2switch-all 
2) feature:install odl-didm-all 
3) feature:install odl-atrium-all 

If you directly install odl-atrium-all first, then you will see the error posted by you.

**Comment by subh007** [comment]
Thanks Manoj,

I am able to install the features as per the mentioned order.
I would suggest we will leave this issue open to be fixed later.

**Comment by mknair75** [comment]
Keeping it in open state as suggested by Subhash.

**Comment by mknair75** [comment]
Closing this issue 
Readme is updated with proper steps
feature configuration is modified to install all the dependent features as part of odl-atrium-all .
