### ISSUE TITLE
Not able to login to dlux and api explorer UI

### ISSUE THREAD

**Issue by subh007** [OpenNetworkingFoundation/ATRIUM#5]
After the installation of bundles I tried to login to dlux ui but it is trowing ERROR 401.

**Comment by mknair75** [comment]
Hope you have installed feature-dlux-all and feature-restconf-all

**Comment by subh007** [comment]
yes, I did.

**Comment by mknair75** [comment]
Following is the order in which I installed the features  after installing odl-l2switch-all, odl-didm-all and odl-atrium-all . I was able to successfully connect to dlux UI and apidocs page. 

feature:install odl-restconf odl-l2switch-switch odl-mdsal-apidocs odl-dlux-core

This is as suggested in the ODL dlux wiki page here 
https://wiki.opendaylight.org/view/OpenDaylight_DLUX:DLUX_Karaf_Feature

**Comment by subh007** [comment]
Hello Manoj,

Thanks for the help. The issue happened because of vm configuration. VM was running with 1 cpu, that I have increased and then I am able to see the proper flows.

But the hosts are still not pinging. I am working on it.

**Comment by subh007** [comment]
Hello Manoj,

I'm seeing that the group entries are not getting installed. 
Could you please confirm that in your setup, whether the group entries are getting installed.

Following is the output of DUT:

```
admin@atrium:~$ sudo ovs-ofctl dump-flows router -O OpenFlow13 table=1
OFPST_FLOW reply (OF1.3) (xid=0x2):
 cookie=0x0, duration=1034.265s, table=1, n_packets=20, n_bytes=1964, priority=180,ip,nw_dst=1.0.0.0/16 actions=write_actions(group:1)
 cookie=0x0, duration=1034.246s, table=1, n_packets=6, n_bytes=592, priority=180,ip,nw_dst=2.0.0.0/16 actions=write_actions(group:2)

admin@atrium:~$ sudo ovs-ofctl dump-groups router -O OpenFlow13
OFPST_GROUP_DESC reply (OF1.3) (xid=0x2):

admin@atrium:~$
```

**Comment by mknair75** [comment]
Hi Subhash,

Following is the output we see for dump-groups

admin@atrium:~$ sudo ovs-ofctl dump-groups router -O OpenFlow13
OFPST_GROUP_DESC reply (OF1.3) (xid=0x2):
 group_id=1,type=indirect,bucket=weight:0,actions=set_field:00:00:00:00:10:01->eth_dst,set_field:00:00:00:00:00:01->eth_src,push_vlan:0x8100,set_field:4196->vlan_vid,output:1
 group_id=2,type=indirect,bucket=weight:0,actions=set_field:00:00:00:00:20:01->eth_dst,set_field:00:00:00:00:00:02->eth_src,push_vlan:0x8100,set_field:4296->vlan_vid,output:2
admin@atrium:~$

Regards

Manoj

**Comment by subh007** [comment]
Hello Manoj,

I recompiled the code and now I am able to see the group entries:

```
> sh ovs-ofctl dump-groups router -O OpenFlow13
OFPST_GROUP_DESC reply (OF1.3) (xid=0x2):
 group_id=1,type=indirect,bucket=weight:0,actions=set_field:00:00:00:00:10:01->eth_dst,set_field:00:00:00:00:00:01->eth_src,push_vlan:0x8100,set_field:4196->vlan_vid,output:1
 group_id=2,type=indirect,bucket=weight:0,actions=set_field:00:00:00:00:20:01->eth_dst,set_field:00:00:00:00:00:02->eth_src,push_vlan:0x8100,set_field:4296->vlan_vid,output:2
```

and hosts are pinging now.

```
mininet> host1 ping host2
*** errRun: ['stty', '-icanon', 'min', '1']
  0PING 2.0.0.1 (2.0.0.1) 56(84) bytes of data.
64 bytes from 2.0.0.1: icmp_req=1 ttl=62 time=2.70 ms
64 bytes from 2.0.0.1: icmp_req=2 ttl=62 time=0.866 ms
64 bytes from 2.0.0.1: icmp_req=3 ttl=62 time=1.37 ms
^CsendInt: writing chr(3)

--- 2.0.0.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2008ms
rtt min/avg/max/mdev = 0.866/1.648/2.706/0.776 ms

mininet> host2 ping host1
*** errRun: ['stty', '-icanon', 'min', '1']
  0PING 1.0.0.1 (1.0.0.1) 56(84) bytes of data.
64 bytes from 1.0.0.1: icmp_req=1 ttl=62 time=2.54 ms
64 bytes from 1.0.0.1: icmp_req=2 ttl=62 time=0.619 ms
```

We can close these issue.

**Comment by mknair75** [comment]
Closing this issue. Subhash is able to launch UI.
