### ISSUE TITLE
Peer routers are not pinging

### ISSUE THREAD

**Issue by subh007** [OpenNetworkingFoundation/ATRIUM#6]
I observed that the peer routers are not pinging, which is not in the case of `atrium-onos` distribution.

```
mininet> peer1 ping 192.168.10.101
*** errRun: ['stty', '-icanon', 'min', '1']
  0PING 192.168.10.101 (192.168.10.101) 56(84) bytes of data.
^CsendInt: writing chr(3)

--- 192.168.10.101 ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 5003ms
```

**Comment by mknair75** [comment]
This will require some code changes . Will update once we fix them.

**Comment by mknair75** [comment]
This is fixed now. Please check the commit below 
https://github.com/OpenNetworkingFoundation/ATRIUM/commit/cb9905072f3e9655efe242cc28329478f02f6380

**Comment by mknair75** [comment]
Closing as Subhash is able to bring up the setup .
